name: main-tests-on_push
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - 'main'
jobs:

  basic-ubuntu-run_tests:
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        python-version: [3.11.1]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest -v
      - name: Run tests
        run: coverage run src/test/app_test.py
      - name: Run tests HTML
        run: coverage html src/test/app_test.py
      - name: Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-html
          path: htmlcov/index.html
      - name: Tests report
        run: coverage report


  basic-self-run_tests:
    runs-on: [self-hosted]

    strategy:
      matrix:
        python-version: [3.11.1]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest -v
      - name: Run tests
        run: coverage run src/test/app_test.py
      - name: Run tests HTML
        run: coverage html src/test/app_test.py
      - name: Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-html
          path: htmlcov/index.html
      - name: Tests report
        run: coverage report
